<?php // this is an autogenerated file - do not edit (created Sun, 17 Apr 2011 21:53:41 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'theseer\\php2odp\\application' => '/application.php',
            'theseer\\php2odp\\cli' => '/cli.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
